name = "live-support-api"
main = "src/index.ts"
compatibility_date = "2026-09-15"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "live-support"
database_id = "930a73f8-0b78-45a2-a514-39fb2edcf704"
migrations_dir = "migrations"

